void futas();
void SIMULATION(double **ter_vektor, bool mentes, int molekulaszam);
double fitness_func(int molekulaszam);
double fRand(double fMin, double fMax);
void windowKey(unsigned char key, int x, int y);
void windowMenu(int value);
void windowSpecial(int key, int x, int y);
void windowMouse(int btn, int state, int x, int y);
void windowPmotion(int x, int y);
void mouseWheel(int scroll, int dir, int x, int y);